//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.30 at 03:49:48 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Statistics" minOccurs="0"/>
 *         &lt;element ref="{}UVMGServer" minOccurs="0"/>
 *         &lt;element ref="{}SSR2" minOccurs="0"/>
 *         &lt;element ref="{}UCCE2" minOccurs="0"/>
 *         &lt;element ref="{}CCOD" minOccurs="0"/>
 *         &lt;element ref="{}MessagingService" minOccurs="0"/>
 *         &lt;element ref="{}Session" minOccurs="0"/>
 *         &lt;element ref="{}SDR" minOccurs="0"/>
 *         &lt;element ref="{}Conference" minOccurs="0"/>
 *         &lt;element ref="{}Clustering" minOccurs="0"/>
 *         &lt;element ref="{}USMLScriptHost" minOccurs="0"/>
 *         &lt;element ref="{}SafeSet" minOccurs="0"/>
 *         &lt;element name="SNMPAgent" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="TargetAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="TargetPort" type="{http://www.w3.org/2001/XMLSchema}int" default="162" />
 *                 &lt;attribute name="ListenPort" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;attribute name="NodeId" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;attribute name="NodeLocation" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *                 &lt;attribute name="NodeName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}VoiceEdit" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="WriteUserDefinedCallID" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="UseDRWRClient" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="USEServerIP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SysWavePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StatisticsLevel" type="{http://www.w3.org/2001/XMLSchema}byte" default="3" />
 *       &lt;attribute name="ListenPort" type="{http://www.w3.org/2001/XMLSchema}int" default="8888" />
 *       &lt;attribute name="ManageServerPort" type="{http://www.w3.org/2001/XMLSchema}int" default="8889" />
 *       &lt;attribute name="RunLog" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="WriteDTMFLog" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="MediaServerIP" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SMSMediaServerIP" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="MaxUserIdleSeconds" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="LogLevel" type="{http://www.w3.org/2001/XMLSchema}string" default="DT" />
 *       &lt;attribute name="IsLinkToUSE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsLinkToICCP" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsDebug" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="AutoClear" type="{http://www.w3.org/2001/XMLSchema}byte" default="0" />
 *       &lt;attribute name="AutoAnswer" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="MaxCallStack" type="{http://www.w3.org/2001/XMLSchema}int" default="300" />
 *       &lt;attribute name="SupportFileOnUnix" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statistics",
    "uvmgServer",
    "ssr2",
    "ucce2",
    "ccod",
    "messagingService",
    "session",
    "sdr",
    "conference",
    "clustering",
    "usmlScriptHost",
    "safeSet",
    "snmpAgent",
    "voiceEdit"
})
@XmlRootElement(name = "AttributeSet")
public class AttributeSet {

    @XmlElement(name = "Statistics")
    protected Statistics statistics;
    @XmlElement(name = "UVMGServer")
    protected UVMGServer uvmgServer;
    @XmlElement(name = "SSR2")
    protected SSR2 ssr2;
    @XmlElement(name = "UCCE2")
    protected UCCE2 ucce2;
    @XmlElement(name = "CCOD")
    protected CCOD ccod;
    @XmlElement(name = "MessagingService")
    protected MessagingService messagingService;
    @XmlElement(name = "Session")
    protected Session session;
    @XmlElement(name = "SDR")
    protected SDR sdr;
    @XmlElement(name = "Conference")
    protected Conference conference;
    @XmlElement(name = "Clustering")
    protected Clustering clustering;
    @XmlElement(name = "USMLScriptHost")
    protected USMLScriptHost usmlScriptHost;
    @XmlElement(name = "SafeSet")
    protected SafeSet safeSet;
    @XmlElement(name = "SNMPAgent")
    protected AttributeSet.SNMPAgent snmpAgent;
    @XmlElement(name = "VoiceEdit")
    protected VoiceEdit voiceEdit;
    @XmlAttribute(name = "WriteUserDefinedCallID")
    protected Boolean writeUserDefinedCallID;
    @XmlAttribute(name = "UseDRWRClient")
    protected Boolean useDRWRClient;
    @XmlAttribute(name = "USEServerIP")
    protected String useServerIP;
    @XmlAttribute(name = "SysWavePath")
    protected String sysWavePath;
    @XmlAttribute(name = "StatisticsLevel")
    protected Byte statisticsLevel;
    @XmlAttribute(name = "ListenPort")
    protected Integer listenPort;
    @XmlAttribute(name = "ManageServerPort")
    protected Integer manageServerPort;
    @XmlAttribute(name = "RunLog")
    protected Boolean runLog;
    @XmlAttribute(name = "WriteDTMFLog")
    protected Boolean writeDTMFLog;
    @XmlAttribute(name = "MediaServerIP", required = true)
    protected String mediaServerIP;
    @XmlAttribute(name = "SMSMediaServerIP")
    protected String smsMediaServerIP;
    @XmlAttribute(name = "MaxUserIdleSeconds")
    protected Integer maxUserIdleSeconds;
    @XmlAttribute(name = "LogLevel")
    protected String logLevel;
    @XmlAttribute(name = "IsLinkToUSE")
    protected Boolean isLinkToUSE;
    @XmlAttribute(name = "IsLinkToICCP")
    protected Boolean isLinkToICCP;
    @XmlAttribute(name = "IsDebug")
    protected Boolean isDebug;
    @XmlAttribute(name = "AutoClear")
    protected Byte autoClear;
    @XmlAttribute(name = "AutoAnswer")
    protected Boolean autoAnswer;
    @XmlAttribute(name = "MaxCallStack")
    protected Integer maxCallStack;
    @XmlAttribute(name = "SupportFileOnUnix")
    protected Boolean supportFileOnUnix;

    /**
     * Gets the value of the statistics property.
     * 
     * @return
     *     possible object is
     *     {@link Statistics }
     *     
     */
    public Statistics getStatistics() {
        return statistics;
    }

    /**
     * Sets the value of the statistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statistics }
     *     
     */
    public void setStatistics(Statistics value) {
        this.statistics = value;
    }

    /**
     * Gets the value of the uvmgServer property.
     * 
     * @return
     *     possible object is
     *     {@link UVMGServer }
     *     
     */
    public UVMGServer getUVMGServer() {
        return uvmgServer;
    }

    /**
     * Sets the value of the uvmgServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link UVMGServer }
     *     
     */
    public void setUVMGServer(UVMGServer value) {
        this.uvmgServer = value;
    }

    /**
     * Gets the value of the ssr2 property.
     * 
     * @return
     *     possible object is
     *     {@link SSR2 }
     *     
     */
    public SSR2 getSSR2() {
        return ssr2;
    }

    /**
     * Sets the value of the ssr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSR2 }
     *     
     */
    public void setSSR2(SSR2 value) {
        this.ssr2 = value;
    }

    /**
     * Gets the value of the ucce2 property.
     * 
     * @return
     *     possible object is
     *     {@link UCCE2 }
     *     
     */
    public UCCE2 getUCCE2() {
        return ucce2;
    }

    /**
     * Sets the value of the ucce2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UCCE2 }
     *     
     */
    public void setUCCE2(UCCE2 value) {
        this.ucce2 = value;
    }

    /**
     * Gets the value of the ccod property.
     * 
     * @return
     *     possible object is
     *     {@link CCOD }
     *     
     */
    public CCOD getCCOD() {
        return ccod;
    }

    /**
     * Sets the value of the ccod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCOD }
     *     
     */
    public void setCCOD(CCOD value) {
        this.ccod = value;
    }

    /**
     * Gets the value of the messagingService property.
     * 
     * @return
     *     possible object is
     *     {@link MessagingService }
     *     
     */
    public MessagingService getMessagingService() {
        return messagingService;
    }

    /**
     * Sets the value of the messagingService property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessagingService }
     *     
     */
    public void setMessagingService(MessagingService value) {
        this.messagingService = value;
    }

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link Session }
     *     
     */
    public Session getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link Session }
     *     
     */
    public void setSession(Session value) {
        this.session = value;
    }

    /**
     * Gets the value of the sdr property.
     * 
     * @return
     *     possible object is
     *     {@link SDR }
     *     
     */
    public SDR getSDR() {
        return sdr;
    }

    /**
     * Sets the value of the sdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SDR }
     *     
     */
    public void setSDR(SDR value) {
        this.sdr = value;
    }

    /**
     * Gets the value of the conference property.
     * 
     * @return
     *     possible object is
     *     {@link Conference }
     *     
     */
    public Conference getConference() {
        return conference;
    }

    /**
     * Sets the value of the conference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conference }
     *     
     */
    public void setConference(Conference value) {
        this.conference = value;
    }

    /**
     * Gets the value of the clustering property.
     * 
     * @return
     *     possible object is
     *     {@link Clustering }
     *     
     */
    public Clustering getClustering() {
        return clustering;
    }

    /**
     * Sets the value of the clustering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clustering }
     *     
     */
    public void setClustering(Clustering value) {
        this.clustering = value;
    }

    /**
     * Gets the value of the usmlScriptHost property.
     * 
     * @return
     *     possible object is
     *     {@link USMLScriptHost }
     *     
     */
    public USMLScriptHost getUSMLScriptHost() {
        return usmlScriptHost;
    }

    /**
     * Sets the value of the usmlScriptHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link USMLScriptHost }
     *     
     */
    public void setUSMLScriptHost(USMLScriptHost value) {
        this.usmlScriptHost = value;
    }

    /**
     * Gets the value of the safeSet property.
     * 
     * @return
     *     possible object is
     *     {@link SafeSet }
     *     
     */
    public SafeSet getSafeSet() {
        return safeSet;
    }

    /**
     * Sets the value of the safeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SafeSet }
     *     
     */
    public void setSafeSet(SafeSet value) {
        this.safeSet = value;
    }

    /**
     * Gets the value of the snmpAgent property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSet.SNMPAgent }
     *     
     */
    public AttributeSet.SNMPAgent getSNMPAgent() {
        return snmpAgent;
    }

    /**
     * Sets the value of the snmpAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSet.SNMPAgent }
     *     
     */
    public void setSNMPAgent(AttributeSet.SNMPAgent value) {
        this.snmpAgent = value;
    }

    /**
     * Gets the value of the voiceEdit property.
     * 
     * @return
     *     possible object is
     *     {@link VoiceEdit }
     *     
     */
    public VoiceEdit getVoiceEdit() {
        return voiceEdit;
    }

    /**
     * Sets the value of the voiceEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoiceEdit }
     *     
     */
    public void setVoiceEdit(VoiceEdit value) {
        this.voiceEdit = value;
    }

    /**
     * Gets the value of the writeUserDefinedCallID property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWriteUserDefinedCallID() {
        if (writeUserDefinedCallID == null) {
            return false;
        } else {
            return writeUserDefinedCallID;
        }
    }

    /**
     * Sets the value of the writeUserDefinedCallID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWriteUserDefinedCallID(Boolean value) {
        this.writeUserDefinedCallID = value;
    }

    /**
     * Gets the value of the useDRWRClient property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseDRWRClient() {
        if (useDRWRClient == null) {
            return false;
        } else {
            return useDRWRClient;
        }
    }

    /**
     * Sets the value of the useDRWRClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseDRWRClient(Boolean value) {
        this.useDRWRClient = value;
    }

    /**
     * Gets the value of the useServerIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSEServerIP() {
        return useServerIP;
    }

    /**
     * Sets the value of the useServerIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSEServerIP(String value) {
        this.useServerIP = value;
    }

    /**
     * Gets the value of the sysWavePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSysWavePath() {
        return sysWavePath;
    }

    /**
     * Sets the value of the sysWavePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSysWavePath(String value) {
        this.sysWavePath = value;
    }

    /**
     * Gets the value of the statisticsLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public byte getStatisticsLevel() {
        if (statisticsLevel == null) {
            return ((byte) 3);
        } else {
            return statisticsLevel;
        }
    }

    /**
     * Sets the value of the statisticsLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setStatisticsLevel(Byte value) {
        this.statisticsLevel = value;
    }

    /**
     * Gets the value of the listenPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getListenPort() {
        if (listenPort == null) {
            return  8888;
        } else {
            return listenPort;
        }
    }

    /**
     * Sets the value of the listenPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setListenPort(Integer value) {
        this.listenPort = value;
    }

    /**
     * Gets the value of the manageServerPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getManageServerPort() {
        if (manageServerPort == null) {
            return  8889;
        } else {
            return manageServerPort;
        }
    }

    /**
     * Sets the value of the manageServerPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setManageServerPort(Integer value) {
        this.manageServerPort = value;
    }

    /**
     * Gets the value of the runLog property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRunLog() {
        if (runLog == null) {
            return false;
        } else {
            return runLog;
        }
    }

    /**
     * Sets the value of the runLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunLog(Boolean value) {
        this.runLog = value;
    }

    /**
     * Gets the value of the writeDTMFLog property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isWriteDTMFLog() {
        if (writeDTMFLog == null) {
            return true;
        } else {
            return writeDTMFLog;
        }
    }

    /**
     * Sets the value of the writeDTMFLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWriteDTMFLog(Boolean value) {
        this.writeDTMFLog = value;
    }

    /**
     * Gets the value of the mediaServerIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaServerIP() {
        return mediaServerIP;
    }

    /**
     * Sets the value of the mediaServerIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaServerIP(String value) {
        this.mediaServerIP = value;
    }

    /**
     * Gets the value of the smsMediaServerIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMSMediaServerIP() {
        if (smsMediaServerIP == null) {
            return "";
        } else {
            return smsMediaServerIP;
        }
    }

    /**
     * Sets the value of the smsMediaServerIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMSMediaServerIP(String value) {
        this.smsMediaServerIP = value;
    }

    /**
     * Gets the value of the maxUserIdleSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxUserIdleSeconds() {
        if (maxUserIdleSeconds == null) {
            return  0;
        } else {
            return maxUserIdleSeconds;
        }
    }

    /**
     * Sets the value of the maxUserIdleSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxUserIdleSeconds(Integer value) {
        this.maxUserIdleSeconds = value;
    }

    /**
     * Gets the value of the logLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogLevel() {
        if (logLevel == null) {
            return "DT";
        } else {
            return logLevel;
        }
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogLevel(String value) {
        this.logLevel = value;
    }

    /**
     * Gets the value of the isLinkToUSE property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsLinkToUSE() {
        if (isLinkToUSE == null) {
            return false;
        } else {
            return isLinkToUSE;
        }
    }

    /**
     * Sets the value of the isLinkToUSE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLinkToUSE(Boolean value) {
        this.isLinkToUSE = value;
    }

    /**
     * Gets the value of the isLinkToICCP property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsLinkToICCP() {
        if (isLinkToICCP == null) {
            return false;
        } else {
            return isLinkToICCP;
        }
    }

    /**
     * Sets the value of the isLinkToICCP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLinkToICCP(Boolean value) {
        this.isLinkToICCP = value;
    }

    /**
     * Gets the value of the isDebug property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsDebug() {
        if (isDebug == null) {
            return false;
        } else {
            return isDebug;
        }
    }

    /**
     * Sets the value of the isDebug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDebug(Boolean value) {
        this.isDebug = value;
    }

    /**
     * Gets the value of the autoClear property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public byte getAutoClear() {
        if (autoClear == null) {
            return ((byte) 0);
        } else {
            return autoClear;
        }
    }

    /**
     * Sets the value of the autoClear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAutoClear(Byte value) {
        this.autoClear = value;
    }

    /**
     * Gets the value of the autoAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAutoAnswer() {
        if (autoAnswer == null) {
            return false;
        } else {
            return autoAnswer;
        }
    }

    /**
     * Sets the value of the autoAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoAnswer(Boolean value) {
        this.autoAnswer = value;
    }

    /**
     * Gets the value of the maxCallStack property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxCallStack() {
        if (maxCallStack == null) {
            return  300;
        } else {
            return maxCallStack;
        }
    }

    /**
     * Sets the value of the maxCallStack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxCallStack(Integer value) {
        this.maxCallStack = value;
    }

    /**
     * Gets the value of the supportFileOnUnix property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSupportFileOnUnix() {
        if (supportFileOnUnix == null) {
            return true;
        } else {
            return supportFileOnUnix;
        }
    }

    /**
     * Sets the value of the supportFileOnUnix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportFileOnUnix(Boolean value) {
        this.supportFileOnUnix = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="TargetAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="TargetPort" type="{http://www.w3.org/2001/XMLSchema}int" default="162" />
     *       &lt;attribute name="ListenPort" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="NodeId" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="NodeLocation" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
     *       &lt;attribute name="NodeName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SNMPAgent {

        @XmlAttribute(name = "TargetAddress")
        protected String targetAddress;
        @XmlAttribute(name = "TargetPort")
        protected Integer targetPort;
        @XmlAttribute(name = "ListenPort")
        protected Integer listenPort;
        @XmlAttribute(name = "NodeId")
        protected Integer nodeId;
        @XmlAttribute(name = "NodeLocation")
        protected String nodeLocation;
        @XmlAttribute(name = "NodeName")
        protected String nodeName;

        /**
         * Gets the value of the targetAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTargetAddress() {
            return targetAddress;
        }

        /**
         * Sets the value of the targetAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTargetAddress(String value) {
            this.targetAddress = value;
        }

        /**
         * Gets the value of the targetPort property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getTargetPort() {
            if (targetPort == null) {
                return  162;
            } else {
                return targetPort;
            }
        }

        /**
         * Sets the value of the targetPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTargetPort(Integer value) {
            this.targetPort = value;
        }

        /**
         * Gets the value of the listenPort property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getListenPort() {
            if (listenPort == null) {
                return  0;
            } else {
                return listenPort;
            }
        }

        /**
         * Sets the value of the listenPort property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setListenPort(Integer value) {
            this.listenPort = value;
        }

        /**
         * Gets the value of the nodeId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getNodeId() {
            if (nodeId == null) {
                return  0;
            } else {
                return nodeId;
            }
        }

        /**
         * Sets the value of the nodeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNodeId(Integer value) {
            this.nodeId = value;
        }

        /**
         * Gets the value of the nodeLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeLocation() {
            if (nodeLocation == null) {
                return "";
            } else {
                return nodeLocation;
            }
        }

        /**
         * Sets the value of the nodeLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeLocation(String value) {
            this.nodeLocation = value;
        }

        /**
         * Gets the value of the nodeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeName() {
            if (nodeName == null) {
                return "";
            } else {
                return nodeName;
            }
        }

        /**
         * Sets the value of the nodeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeName(String value) {
            this.nodeName = value;
        }

    }

}
