//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="XMLFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IsInbound" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="IsAutoStart" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Application")
public class Application {

    @XmlAttribute(name = "XMLFile", required = true)
    protected String xmlFile;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "IsInbound", required = true)
    protected boolean isInbound;
    @XmlAttribute(name = "IsAutoStart", required = true)
    protected boolean isAutoStart;

    /**
     * Gets the value of the xmlFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLFile() {
        return xmlFile;
    }

    /**
     * Sets the value of the xmlFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLFile(String value) {
        this.xmlFile = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isInbound property.
     * 
     */
    public boolean isIsInbound() {
        return isInbound;
    }

    /**
     * Sets the value of the isInbound property.
     * 
     */
    public void setIsInbound(boolean value) {
        this.isInbound = value;
    }

    /**
     * Gets the value of the isAutoStart property.
     * 
     */
    public boolean isIsAutoStart() {
        return isAutoStart;
    }

    /**
     * Sets the value of the isAutoStart property.
     * 
     */
    public void setIsAutoStart(boolean value) {
        this.isAutoStart = value;
    }

}
