//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.12 at 04:21:46 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="GLSConnection" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="SleeServiceName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="CMSServerPort" type="{http://www.w3.org/2001/XMLSchema}int" default="11112" />
 *       &lt;attribute name="StatFileDir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ServiceID" type="{http://www.w3.org/2001/XMLSchema}string" default="USE_Service" />
 *       &lt;attribute name="AgentServiceID" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="UseSSL" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="SupportVideo" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="OutboundCMS" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "CCOD")
public class CCOD {

    @XmlAttribute(name = "GLSConnection")
    protected String glsConnection;
    @XmlAttribute(name = "SleeServiceName")
    protected String sleeServiceName;
    @XmlAttribute(name = "CMSServerPort")
    protected Integer cmsServerPort;
    @XmlAttribute(name = "StatFileDir")
    protected String statFileDir;
    @XmlAttribute(name = "ServiceID")
    protected String serviceID;
    @XmlAttribute(name = "AgentServiceID")
    protected String agentServiceID;
    @XmlAttribute(name = "UseSSL")
    protected Boolean useSSL;
    @XmlAttribute(name = "SupportVideo")
    protected Boolean supportVideo;
    @XmlAttribute(name = "OutboundCMS")
    protected String outboundCMS;

    /**
     * Gets the value of the glsConnection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLSConnection() {
        if (glsConnection == null) {
            return "";
        } else {
            return glsConnection;
        }
    }

    /**
     * Sets the value of the glsConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLSConnection(String value) {
        this.glsConnection = value;
    }

    /**
     * Gets the value of the sleeServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSleeServiceName() {
        if (sleeServiceName == null) {
            return "";
        } else {
            return sleeServiceName;
        }
    }

    /**
     * Sets the value of the sleeServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSleeServiceName(String value) {
        this.sleeServiceName = value;
    }

    /**
     * Gets the value of the cmsServerPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCMSServerPort() {
        if (cmsServerPort == null) {
            return  11112;
        } else {
            return cmsServerPort;
        }
    }

    /**
     * Sets the value of the cmsServerPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCMSServerPort(Integer value) {
        this.cmsServerPort = value;
    }

    /**
     * Gets the value of the statFileDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatFileDir() {
        return statFileDir;
    }

    /**
     * Sets the value of the statFileDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatFileDir(String value) {
        this.statFileDir = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        if (serviceID == null) {
            return "USE_Service";
        } else {
            return serviceID;
        }
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the agentServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentServiceID() {
        if (agentServiceID == null) {
            return "";
        } else {
            return agentServiceID;
        }
    }

    /**
     * Sets the value of the agentServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentServiceID(String value) {
        this.agentServiceID = value;
    }

    /**
     * Gets the value of the useSSL property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseSSL() {
        if (useSSL == null) {
            return false;
        } else {
            return useSSL;
        }
    }

    /**
     * Sets the value of the useSSL property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseSSL(Boolean value) {
        this.useSSL = value;
    }

    /**
     * Gets the value of the supportVideo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSupportVideo() {
        if (supportVideo == null) {
            return false;
        } else {
            return supportVideo;
        }
    }

    /**
     * Sets the value of the supportVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportVideo(Boolean value) {
        this.supportVideo = value;
    }

    /**
     * Gets the value of the outboundCMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutboundCMS() {
        if (outboundCMS == null) {
            return "";
        } else {
            return outboundCMS;
        }
    }

    /**
     * Sets the value of the outboundCMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutboundCMS(String value) {
        this.outboundCMS = value;
    }

}
