//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SSRServerIP" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IsConnectSSR" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Clustering")
public class Clustering {

    @XmlAttribute(name = "SSRServerIP", required = true)
    protected String ssrServerIP;
    @XmlAttribute(name = "IsConnectSSR", required = true)
    protected boolean isConnectSSR;

    /**
     * Gets the value of the ssrServerIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSRServerIP() {
        return ssrServerIP;
    }

    /**
     * Sets the value of the ssrServerIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSRServerIP(String value) {
        this.ssrServerIP = value;
    }

    /**
     * Gets the value of the isConnectSSR property.
     * 
     */
    public boolean isIsConnectSSR() {
        return isConnectSSR;
    }

    /**
     * Sets the value of the isConnectSSR property.
     * 
     */
    public void setIsConnectSSR(boolean value) {
        this.isConnectSSR = value;
    }

}
