//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ComplexDN"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "complexDN"
})
@XmlRootElement(name = "DNList")
public class DNList {

    @XmlElement(name = "ComplexDN", required = true)
    protected ComplexDN complexDN;

    /**
     * Gets the value of the complexDN property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexDN }
     *     
     */
    public ComplexDN getComplexDN() {
        return complexDN;
    }

    /**
     * Sets the value of the complexDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexDN }
     *     
     */
    public void setComplexDN(ComplexDN value) {
        this.complexDN = value;
    }

}
