//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DefaultMessageTTL" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *       &lt;attribute name="InternalQueueName" type="{http://www.w3.org/2001/XMLSchema}string" default="SLEE_Internal_Queue" />
 *       &lt;attribute name="SessionTTL" type="{http://www.w3.org/2001/XMLSchema}int" default="172800" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MessagingService")
public class MessagingService {

    @XmlAttribute(name = "DefaultMessageTTL")
    protected Integer defaultMessageTTL;
    @XmlAttribute(name = "InternalQueueName")
    protected String internalQueueName;
    @XmlAttribute(name = "SessionTTL")
    protected Integer sessionTTL;

    /**
     * Gets the value of the defaultMessageTTL property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDefaultMessageTTL() {
        if (defaultMessageTTL == null) {
            return -1;
        } else {
            return defaultMessageTTL;
        }
    }

    /**
     * Sets the value of the defaultMessageTTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultMessageTTL(Integer value) {
        this.defaultMessageTTL = value;
    }

    /**
     * Gets the value of the internalQueueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalQueueName() {
        if (internalQueueName == null) {
            return "SLEE_Internal_Queue";
        } else {
            return internalQueueName;
        }
    }

    /**
     * Sets the value of the internalQueueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalQueueName(String value) {
        this.internalQueueName = value;
    }

    /**
     * Gets the value of the sessionTTL property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSessionTTL() {
        if (sessionTTL == null) {
            return  172800;
        } else {
            return sessionTTL;
        }
    }

    /**
     * Sets the value of the sessionTTL property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSessionTTL(Integer value) {
        this.sessionTTL = value;
    }

}
