//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SafeTime" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MaxMem" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MaxErrCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="IsStart" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SafeSet")
public class SafeSet {

    @XmlAttribute(name = "SafeTime", required = true)
    protected byte safeTime;
    @XmlAttribute(name = "MaxMem", required = true)
    protected int maxMem;
    @XmlAttribute(name = "MaxErrCount", required = true)
    protected int maxErrCount;
    @XmlAttribute(name = "IsStart", required = true)
    protected boolean isStart;

    /**
     * Gets the value of the safeTime property.
     * 
     */
    public byte getSafeTime() {
        return safeTime;
    }

    /**
     * Sets the value of the safeTime property.
     * 
     */
    public void setSafeTime(byte value) {
        this.safeTime = value;
    }

    /**
     * Gets the value of the maxMem property.
     * 
     */
    public int getMaxMem() {
        return maxMem;
    }

    /**
     * Sets the value of the maxMem property.
     * 
     */
    public void setMaxMem(int value) {
        this.maxMem = value;
    }

    /**
     * Gets the value of the maxErrCount property.
     * 
     */
    public int getMaxErrCount() {
        return maxErrCount;
    }

    /**
     * Sets the value of the maxErrCount property.
     * 
     */
    public void setMaxErrCount(int value) {
        this.maxErrCount = value;
    }

    /**
     * Gets the value of the isStart property.
     * 
     */
    public boolean isIsStart() {
        return isStart;
    }

    /**
     * Sets the value of the isStart property.
     * 
     */
    public void setIsStart(boolean value) {
        this.isStart = value;
    }

}
