//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.12 at 03:39:41 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ReasoningProvider" maxOccurs="10" minOccurs="0"/>
 *         &lt;element ref="{}CallEventListener" maxOccurs="10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reasoningProvider",
    "callEventListener"
})
@XmlRootElement(name = "ServiceProviders")
public class ServiceProviders {

    @XmlElement(name = "ReasoningProvider")
    protected List<ReasoningProvider> reasoningProvider;
    @XmlElement(name = "CallEventListener")
    protected List<CallEventListener> callEventListener;

    /**
     * Gets the value of the reasoningProvider property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reasoningProvider property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReasoningProvider().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReasoningProvider }
     * 
     * 
     */
    public List<ReasoningProvider> getReasoningProvider() {
        if (reasoningProvider == null) {
            reasoningProvider = new ArrayList<ReasoningProvider>();
        }
        return this.reasoningProvider;
    }

    /**
     * Gets the value of the callEventListener property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the callEventListener property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCallEventListener().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CallEventListener }
     * 
     * 
     */
    public List<CallEventListener> getCallEventListener() {
        if (callEventListener == null) {
            callEventListener = new ArrayList<CallEventListener>();
        }
        return this.callEventListener;
    }

}
