//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="MaxSessionCount" type="{http://www.w3.org/2001/XMLSchema}int" default="10000" />
 *       &lt;attribute name="TimeoutSeconds" type="{http://www.w3.org/2001/XMLSchema}int" default="172800" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Session")
public class Session {

    @XmlAttribute(name = "MaxSessionCount")
    protected Integer maxSessionCount;
    @XmlAttribute(name = "TimeoutSeconds")
    protected Integer timeoutSeconds;

    /**
     * Gets the value of the maxSessionCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxSessionCount() {
        if (maxSessionCount == null) {
            return  10000;
        } else {
            return maxSessionCount;
        }
    }

    /**
     * Sets the value of the maxSessionCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxSessionCount(Integer value) {
        this.maxSessionCount = value;
    }

    /**
     * Gets the value of the timeoutSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTimeoutSeconds() {
        if (timeoutSeconds == null) {
            return  172800;
        } else {
            return timeoutSeconds;
        }
    }

    /**
     * Sets the value of the timeoutSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeoutSeconds(Integer value) {
        this.timeoutSeconds = value;
    }

}
