//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="WorkTime" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="QueueCount" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="HaveLimitedSafeMode" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "USMLScriptHost")
public class USMLScriptHost {

    @XmlAttribute(name = "WorkTime", required = true)
    protected short workTime;
    @XmlAttribute(name = "QueueCount", required = true)
    protected byte queueCount;
    @XmlAttribute(name = "HaveLimitedSafeMode", required = true)
    protected boolean haveLimitedSafeMode;

    /**
     * Gets the value of the workTime property.
     * 
     */
    public short getWorkTime() {
        return workTime;
    }

    /**
     * Sets the value of the workTime property.
     * 
     */
    public void setWorkTime(short value) {
        this.workTime = value;
    }

    /**
     * Gets the value of the queueCount property.
     * 
     */
    public byte getQueueCount() {
        return queueCount;
    }

    /**
     * Sets the value of the queueCount property.
     * 
     */
    public void setQueueCount(byte value) {
        this.queueCount = value;
    }

    /**
     * Gets the value of the haveLimitedSafeMode property.
     * 
     */
    public boolean isHaveLimitedSafeMode() {
        return haveLimitedSafeMode;
    }

    /**
     * Sets the value of the haveLimitedSafeMode property.
     * 
     */
    public void setHaveLimitedSafeMode(boolean value) {
        this.haveLimitedSafeMode = value;
    }

}
