//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="StartDN" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="EndDN" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ComplexDN")
public class ComplexDN {

    @XmlAttribute(name = "StartDN", required = true)
    protected int startDN;
    @XmlAttribute(name = "EndDN", required = true)
    protected int endDN;

    /**
     * Gets the value of the startDN property.
     * 
     */
    public int getStartDN() {
        return startDN;
    }

    /**
     * Sets the value of the startDN property.
     * 
     */
    public void setStartDN(int value) {
        this.startDN = value;
    }

    /**
     * Gets the value of the endDN property.
     * 
     */
    public int getEndDN() {
        return endDN;
    }

    /**
     * Sets the value of the endDN property.
     * 
     */
    public void setEndDN(int value) {
        this.endDN = value;
    }

}
