//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.30 at 03:49:48 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="IP" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="Port" type="{http://www.w3.org/2001/XMLSchema}int" default="12000" />
 *       &lt;attribute name="SLEEName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="SLEEPassword" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "UCCE2")
public class UCCE2 {

    @XmlAttribute(name = "IP")
    protected String ip;
    @XmlAttribute(name = "Port")
    protected Integer port;
    @XmlAttribute(name = "SLEEName")
    protected String sleeName;
    @XmlAttribute(name = "SLEEPassword")
    protected String sleePassword;

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIP() {
        if (ip == null) {
            return "";
        } else {
            return ip;
        }
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIP(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getPort() {
        if (port == null) {
            return  12000;
        } else {
            return port;
        }
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPort(Integer value) {
        this.port = value;
    }

    /**
     * Gets the value of the sleeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLEEName() {
        if (sleeName == null) {
            return "";
        } else {
            return sleeName;
        }
    }

    /**
     * Sets the value of the sleeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLEEName(String value) {
        this.sleeName = value;
    }

    /**
     * Gets the value of the sleePassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLEEPassword() {
        if (sleePassword == null) {
            return "";
        } else {
            return sleePassword;
        }
    }

    /**
     * Sets the value of the sleePassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLEEPassword(String value) {
        this.sleePassword = value;
    }

}
