//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.channelsoft.slee.unifiedservicemanagement.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.channelsoft.slee.unifiedservicemanagement.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttributeSet }
     * 
     */
    public AttributeSet createAttributeSet() {
        return new AttributeSet();
    }

    /**
     * Create an instance of {@link ATSE.Components.Component.Config.Entry }
     * 
     */
    public ATSE.Components.Component.Config.Entry createATSEComponentsComponentConfigEntry() {
        return new ATSE.Components.Component.Config.Entry();
    }

    /**
     * Create an instance of {@link RunTime }
     * 
     */
    public RunTime createRunTime() {
        return new RunTime();
    }

    /**
     * Create an instance of {@link SDR }
     * 
     */
    public SDR createSDR() {
        return new SDR();
    }

    /**
     * Create an instance of {@link ATSE }
     * 
     */
    public ATSE createATSE() {
        return new ATSE();
    }

    /**
     * Create an instance of {@link AttributeSet.SNMPAgent }
     * 
     */
    public AttributeSet.SNMPAgent createAttributeSetSNMPAgent() {
        return new AttributeSet.SNMPAgent();
    }

    /**
     * Create an instance of {@link SSR2 }
     * 
     */
    public SSR2 createSSR2() {
        return new SSR2();
    }

    /**
     * Create an instance of {@link ATSE.Components }
     * 
     */
    public ATSE.Components createATSEComponents() {
        return new ATSE.Components();
    }

    /**
     * Create an instance of {@link ATSE.Components.Component }
     * 
     */
    public ATSE.Components.Component createATSEComponentsComponent() {
        return new ATSE.Components.Component();
    }

    /**
     * Create an instance of {@link UVMGServer }
     * 
     */
    public UVMGServer createUVMGServer() {
        return new UVMGServer();
    }

    /**
     * Create an instance of {@link ATSE.UserDefined }
     * 
     */
    public ATSE.UserDefined createATSEUserDefined() {
        return new ATSE.UserDefined();
    }

    /**
     * Create an instance of {@link ReasoningProvider.Config.Entry }
     * 
     */
    public ReasoningProvider.Config.Entry createReasoningProviderConfigEntry() {
        return new ReasoningProvider.Config.Entry();
    }

    /**
     * Create an instance of {@link DBPool }
     * 
     */
    public DBPool createDBPool() {
        return new DBPool();
    }

    /**
     * Create an instance of {@link VoiceEdit }
     * 
     */
    public VoiceEdit createVoiceEdit() {
        return new VoiceEdit();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link ServiceProviders }
     * 
     */
    public ServiceProviders createServiceProviders() {
        return new ServiceProviders();
    }

    /**
     * Create an instance of {@link ComplexDN }
     * 
     */
    public ComplexDN createComplexDN() {
        return new ComplexDN();
    }

    /**
     * Create an instance of {@link ReasoningProvider.Config }
     * 
     */
    public ReasoningProvider.Config createReasoningProviderConfig() {
        return new ReasoningProvider.Config();
    }

    /**
     * Create an instance of {@link ATSE.Components.Component.Config }
     * 
     */
    public ATSE.Components.Component.Config createATSEComponentsComponentConfig() {
        return new ATSE.Components.Component.Config();
    }

    /**
     * Create an instance of {@link CCOD }
     * 
     */
    public CCOD createCCOD() {
        return new CCOD();
    }

    /**
     * Create an instance of {@link JMSPool }
     * 
     */
    public JMSPool createJMSPool() {
        return new JMSPool();
    }

    /**
     * Create an instance of {@link DNGroups }
     * 
     */
    public DNGroups createDNGroups() {
        return new DNGroups();
    }

    /**
     * Create an instance of {@link RunPeriod }
     * 
     */
    public RunPeriod createRunPeriod() {
        return new RunPeriod();
    }

    /**
     * Create an instance of {@link DBPools }
     * 
     */
    public DBPools createDBPools() {
        return new DBPools();
    }

    /**
     * Create an instance of {@link Conference }
     * 
     */
    public Conference createConference() {
        return new Conference();
    }

    /**
     * Create an instance of {@link DNList }
     * 
     */
    public DNList createDNList() {
        return new DNList();
    }

    /**
     * Create an instance of {@link ReasoningProvider }
     * 
     */
    public ReasoningProvider createReasoningProvider() {
        return new ReasoningProvider();
    }

    /**
     * Create an instance of {@link Clustering }
     * 
     */
    public Clustering createClustering() {
        return new Clustering();
    }

    /**
     * Create an instance of {@link SafeSet }
     * 
     */
    public SafeSet createSafeSet() {
        return new SafeSet();
    }

    /**
     * Create an instance of {@link JMSPools }
     * 
     */
    public JMSPools createJMSPools() {
        return new JMSPools();
    }

    /**
     * Create an instance of {@link USMLScriptHost }
     * 
     */
    public USMLScriptHost createUSMLScriptHost() {
        return new USMLScriptHost();
    }

    /**
     * Create an instance of {@link ATSE.UserDefined.Entry }
     * 
     */
    public ATSE.UserDefined.Entry createATSEUserDefinedEntry() {
        return new ATSE.UserDefined.Entry();
    }

    /**
     * Create an instance of {@link MessagingService }
     * 
     */
    public MessagingService createMessagingService() {
        return new MessagingService();
    }

    /**
     * Create an instance of {@link ResGroup }
     * 
     */
    public ResGroup createResGroup() {
        return new ResGroup();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link Statistics }
     * 
     */
    public Statistics createStatistics() {
        return new Statistics();
    }

}
