//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RunPeriod"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "runPeriod"
})
@XmlRootElement(name = "RunTime")
public class RunTime {

    @XmlElement(name = "RunPeriod", required = true)
    protected RunPeriod runPeriod;

    /**
     * Gets the value of the runPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link RunPeriod }
     *     
     */
    public RunPeriod getRunPeriod() {
        return runPeriod;
    }

    /**
     * Sets the value of the runPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunPeriod }
     *     
     */
    public void setRunPeriod(RunPeriod value) {
        this.runPeriod = value;
    }

}
