//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 03:00:58 ÏÂÎç CST 
//


package com.channelsoft.slee.unifiedservicemanagement.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InitialContextFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InitCapacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MaxCapacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ProviderUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "initialContextFactory",
    "initCapacity",
    "maxCapacity",
    "providerUrl"
})
@XmlRootElement(name = "JMSPool")
public class JMSPool {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "InitialContextFactory", required = true)
    protected String initialContextFactory;
    @XmlElement(name = "InitCapacity", defaultValue = "1")
    protected int initCapacity;
    @XmlElement(name = "MaxCapacity", defaultValue = "1")
    protected int maxCapacity;
    @XmlElement(name = "ProviderUrl", required = true)
    protected String providerUrl;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the initialContextFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialContextFactory() {
        return initialContextFactory;
    }

    /**
     * Sets the value of the initialContextFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialContextFactory(String value) {
        this.initialContextFactory = value;
    }

    /**
     * Gets the value of the initCapacity property.
     * 
     */
    public int getInitCapacity() {
        return initCapacity;
    }

    /**
     * Sets the value of the initCapacity property.
     * 
     */
    public void setInitCapacity(int value) {
        this.initCapacity = value;
    }

    /**
     * Gets the value of the maxCapacity property.
     * 
     */
    public int getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * Sets the value of the maxCapacity property.
     * 
     */
    public void setMaxCapacity(int value) {
        this.maxCapacity = value;
    }

    /**
     * Gets the value of the providerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderUrl() {
        return providerUrl;
    }

    /**
     * Sets the value of the providerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderUrl(String value) {
        this.providerUrl = value;
    }

}
